version: '3.8'
services:
  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    image: custom-airflow:latest
    container_name: airflow
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=airflowfernetkeyairflowfernetkey
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=airflowsecretkeyairflowsecretkey
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__WEBSERVER__PORT=8081
    ports:
      - "8081:8081"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/requirements.txt:/requirements.txt
    depends_on: []
    command: >
      bash -c "
        pip install --no-cache-dir -r /requirements.txt &&
        airflow db upgrade &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
        airflow webserver --port 8081
      "
    networks:
      - iceberg_default
      - delta_default
networks:
  iceberg_default:
    external: true
  delta_default:
    external: true 