version: '3.8'

services:
  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: iceberg-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # PostgreSQL Database (Metastore)
  postgres:
    image: postgres:15
    container_name: iceberg-postgres
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d metastore"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Hive Metastore
  hive-metastore:
    image: apache/hive:3.1.3
    container_name: iceberg-hive-metastore
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_NAME: metastore
      DB_USER: hive
      DB_PASSWORD: hive
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9083/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Trino Server
  trino:
    image: trinodb/trino:latest
    container_name: iceberg-trino
    ports:
      - "8080:8080"
    volumes:
      - ./etc:/etc/trino
    depends_on:
      hive-metastore:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/info"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  minio_data:
  postgres_data:
