version: '3.8'

services:
  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: delta-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # PostgreSQL Database (Metastore)
  postgres:
    image: postgres:15
    container_name: delta-postgres
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d metastore"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Hive Metastore
  hive-metastore:
    image: apache/hive:3.1.3
    container_name: delta-hive-metastore
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_NAME: metastore
      DB_USER: hive
      DB_PASSWORD: hive
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9083/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Spark Master
  spark-master:
    image: bitnami/spark:3.5
    container_name: delta-spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark-config:/opt/spark/conf
      - ./spark-apps:/opt/spark-apps
      - ./spark-extra-jars:/opt/spark/extra-jars
    depends_on:
      - hive-metastore
    networks:
      - default
      - lakehouse

  spark-worker:
    image: bitnami/spark:3.5
    container_name: delta-spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark-config:/opt/bitnami/spark/conf
      - ./spark-apps:/opt/spark-apps

  hive-metastore:
    build:
      context: .
      dockerfile: Dockerfile
    image: delta-hive:3.1.3
    entrypoint: ["/opt/hive/bin/hive"]
    command: ["--service", "metastore"]
    environment:
      - DB_DRIVER=postgres
      - HIVE_CUSTOM_CONF_DIR=/opt/hive/conf
      - HIVE_AUX_JARS_PATH=/opt/hive/extra-jars
    volumes:
      - ./hive-config:/opt/hive/conf
      - ./hive-extra-jars:/opt/hive/extra-jars
    depends_on:
      spark-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  minio_data:
  postgres_data:
