version: '3.8'

services:
  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=metastore_db
    ports:
      - "5432:5432"
    # ggf. weitere Konfiguration (Volumes etc.)

  spark-master:
    image: apache/spark:3.5.3
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8090:8080"
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark-config:/opt/spark/conf
      - ./spark-apps:/opt/spark-apps
      - ./spark-extra-jars:/opt/spark/extra-jars
      - ./spark-extra-jars/delta-spark_2.12-3.2.0.jar:/opt/spark/jars/delta-spark_2.12-3.2.0.jar:ro
      - ./spark-extra-jars/delta_spark-3.2.0-py3-none-any.whl:/opt/spark/extra-jars/delta_spark-3.2.0-py3-none-any.whl:ro
      - ./spark-extra-jars/delta-storage-3.2.0.jar:/opt/spark/jars/delta-storage-3.2.0.jar:ro
      - ./spark-extra-jars/postgresql-42.7.3.jar:/opt/spark/jars/postgresql-42.7.3.jar:ro
    depends_on:
      - hive-metastore
    networks:
      - default
      - lakehouse

  spark-worker:
    image: apache/spark:3.5.3
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    depends_on:
      spark-master:
        condition: service_started
    volumes:
      - ./spark-config:/opt/spark/conf
      - ./spark-apps:/opt/spark-apps
      - ./spark-extra-jars/delta-spark_2.12-3.2.0.jar:/opt/spark/jars/delta-spark_2.12-3.2.0.jar:ro
      - ./spark-extra-jars/delta_spark-3.2.0-py3-none-any.whl:/opt/spark/extra-jars/delta_spark-3.2.0-py3-none-any.whl:ro
      - ./spark-extra-jars/delta-storage-3.2.0.jar:/opt/spark/jars/delta-storage-3.2.0.jar:ro
      - ./spark-extra-jars/postgresql-42.7.3.jar:/opt/spark/jars/postgresql-42.7.3.jar:ro

  hive-metastore:
    build:
      context: .
      dockerfile: Dockerfile
    image: delta-hive:3.1.3
    entrypoint: ["/opt/hive/bin/hive"]
    command: ["--service", "metastore"]
    environment:
      - DB_DRIVER=postgres
      - HIVE_CUSTOM_CONF_DIR=/opt/hive/conf
      - HIVE_AUX_JARS_PATH=/opt/hive/extra-jars
    volumes:
      - ./hive-config:/opt/hive/conf
      - ./hive-extra-jars:/opt/hive/extra-jars
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9083"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
      - lakehouse

  # MinIO-Service für S3-kompatiblen Speicher
  minio:
    image: minio/minio:RELEASE.2024-01-13T07-53-03Z
    environment:
      - MINIO_ROOT_USER=accesskey
      - MINIO_ROOT_PASSWORD=secretkey
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9003:9001"
    volumes:
      - ./test-data:/data
    networks:
      - default
      - lakehouse

networks:
  default:
    driver: bridge
  lakehouse:
    driver: bridge

# Volume für MinIO-Daten
volumes:
  minio-data: